import Link from "next/link";
import { APP_NAME, SITE_URL } from "@/lib/constants";
import { LegalList, LegalProse, LegalSection } from "@/components/legal/LegalProse";

const linkClass = "text-foreground underline-offset-4 hover:underline";

export function DisclaimerContent() {
  const updated = "September 19, 2026";

  return (
    <LegalProse>
      <p className="text-sm text-muted-foreground">
        <strong className="font-medium text-foreground">Last Updated:</strong> {updated}
      </p>

      <LegalSection title="1. General Information">
        <p>The information provided on {APP_NAME} is intended for general informational and practical purposes.</p>
        <p>
          {APP_NAME} does not guarantee that all information, tool results, descriptions, or other content available on
          the website will always be complete, accurate, current, or suitable for every individual use case.
        </p>
        <p>
          You are responsible for evaluating the results generated by our tools before relying on them for important
          purposes.
        </p>
      </LegalSection>

      <LegalSection title="2. Image Processing Results">
        <p>{APP_NAME} provides tools for common image tasks, including:</p>
        <LegalList items={["Image Compression", "Image Resizing", "Image Cropping", "Image Conversion"]} />
        <p>
          The result produced by these tools may vary depending on the original file, selected settings, image format,
          dimensions, quality settings, and other technical factors.
        </p>
        <p>
          For example, image compression may produce different file sizes and visual results depending on the original
          image and selected target size.
        </p>
        <p>A selected target file size does not guarantee an exact final file size in every situation.</p>
      </LegalSection>

      <LegalSection title="3. No Guarantee of Specific Results">
        <p>
          While we aim to make our tools useful and reliable, {APP_NAME} does not guarantee that the output produced by
          any tool will meet a particular technical requirement or intended use.
        </p>
        <p>You should review the processed file before using it for:</p>
        <LegalList
          items={[
            "Professional work",
            "Business purposes",
            "Legal documents",
            "Academic submissions",
            "Government requirements",
            "Publishing",
            "Printing",
            "Website uploads",
            "Other important purposes",
          ]}
        />
      </LegalSection>

      <LegalSection title="4. Uploaded Files">
        <p>
          Users are responsible for the files they upload to {APP_NAME} and must have the necessary rights and permissions
          to use and process those files.
        </p>
        <p>{APP_NAME} processes uploaded images for the specific operation requested by the user.</p>
        <p>
          Uploaded image files are processed temporarily and removed after processing. Image files are not stored as
          permanent files in our database.
        </p>
        <p>{APP_NAME} should not be treated as a permanent file-storage or backup service.</p>
        <p>Users should maintain their own backups of important files.</p>
      </LegalSection>

      <LegalSection title="5. Service Availability">
        <p>
          We make reasonable efforts to keep {APP_NAME} available and functional. However, we do not guarantee
          uninterrupted or error-free access to the website or its tools.
        </p>
        <p>The service may be temporarily unavailable because of:</p>
        <LegalList
          items={[
            "Maintenance",
            "Software updates",
            "Technical issues",
            "Server or hosting problems",
            "Security incidents",
            "Third-party service interruptions",
            "Network problems",
            "Circumstances outside our reasonable control",
          ]}
        />
        <p>Features and tools may also be modified, updated, suspended, or discontinued where necessary.</p>
      </LegalSection>

      <LegalSection title="6. Third-Party Services">
        <p>
          {APP_NAME} may use third-party services for authentication, hosting, databases, security, analytics,
          advertising, and other technical functions.
        </p>
        <p>Third-party services operate independently and may have their own terms, policies, and limitations.</p>
        <p>
          {APP_NAME} is not responsible for the availability, performance, content, or policies of third-party services.
        </p>
      </LegalSection>

      <LegalSection title="7. Advertising and External Links">
        <p>{APP_NAME} may display advertisements or links to third-party websites and services.</p>
        <p>
          The presence of an advertisement or external link does not constitute an endorsement, recommendation, or
          guarantee by {APP_NAME}.
        </p>
        <p>
          We are not responsible for the content, availability, privacy practices, security, products, or services
          provided by external websites.
        </p>
        <p>Users should review the applicable terms and privacy policies of third-party websites before using them.</p>
      </LegalSection>

      <LegalSection title="8. No Professional Advice">
        <p>
          The information available on {APP_NAME} is not intended to provide legal, financial, medical, technical, or
          other professional advice.
        </p>
        <p>
          If you require professional advice, you should consult a qualified professional who can evaluate your specific
          situation.
        </p>
      </LegalSection>

      <LegalSection title="9. User Responsibility">
        <p>You are responsible for how you use {APP_NAME} and the results produced by its tools.</p>
        <p>Before relying on a processed file, you should verify that:</p>
        <LegalList
          items={[
            "The file is complete",
            "The file opens correctly",
            "The image quality is acceptable",
            "The dimensions are correct",
            "The format is suitable for your intended use",
            "The file meets any specific requirements of the platform or service where you intend to use it",
          ]}
        />
      </LegalSection>

      <LegalSection title="10. Limitation of Liability">
        <p>
          To the maximum extent permitted by applicable law, {APP_NAME} and its operators will not be responsible for
          losses or damages resulting from your use of, or inability to use, the website or its tools.
        </p>
        <p>This may include, but is not limited to:</p>
        <LegalList
          items={[
            "Loss of data",
            "Loss of files",
            "Business interruption",
            "Loss of profits",
            "Technical problems",
            "Incorrect or unexpected processing results",
            "Service interruptions",
            "Reliance on information provided through the website",
          ]}
        />
        <p>
          Nothing in this Disclaimer is intended to exclude or limit liability where such limitation is not permitted by
          applicable law.
        </p>
      </LegalSection>

      <LegalSection title="11. Changes to This Disclaimer">
        <p>
          We may update this Disclaimer from time to time to reflect changes to {APP_NAME}, its services, features, or
          applicable requirements.
        </p>
        <p>When changes are made, the &quot;Last Updated&quot; date will be updated accordingly.</p>
        <p>We encourage users to review this page periodically.</p>
      </LegalSection>

      <LegalSection title="12. Acceptance of This Disclaimer">
        <p>
          By accessing or using {APP_NAME}, you acknowledge that you have read and understood this Disclaimer and agree to
          use the website and its tools at your own discretion and responsibility.
        </p>
        <p>If you do not agree with this Disclaimer, please discontinue use of {APP_NAME}.</p>
      </LegalSection>

      <LegalSection title="13. Contact Us">
        <p>If you have questions about this Disclaimer or the use of {APP_NAME}, please contact us.</p>
        <p>
          <strong className="font-medium text-foreground">Website:</strong> {APP_NAME}
        </p>
        <p>
          <strong className="font-medium text-foreground">Website URL:</strong>{" "}
          <Link href={SITE_URL} className={linkClass}>{SITE_URL}</Link>
        </p>
        <p>
          <strong className="font-medium text-foreground">Email:</strong>{" "}
          <Link href="/contact" className={linkClass}>Contact form</Link> on our website.
        </p>
      </LegalSection>
    </LegalProse>
  );
}
